version: '3.9'
services:
  database:
    container_name: vuttr_db
    image: postgres:latest
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_PORT=${PG_PORT}
      - POSTGRES_USER=${PG_USERNAME}
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - ./db:/var/lib/postgresql/database
    networks:
      - vuttr_network
networks:
  vuttr_network:
    driver: bridge
